### ISSUE TITLE
Working with video.

### ISSUE THREAD

**Issue by juanpiterson** [Jerameel/Echo#1]
Hello there.
This isn't an issue, it is more like one help request.

I'm trying to use kurento as middle server for one react-native-webrtc app, for storing the video conferences.

What do i need to do in this demo, for instead of audio, send and receive video.

**Comment by Jerameel** [comment]
I have it working, what you'll need is to modify kurento's java group call since js is not available. For React-Native, You might just need to switch to WebSocket instead of Socket IO if ever you're using one since the java demo is using WebSockets.

**Comment by juanpiterson** [comment]
Ok thanks,
Do you know where i can find kurento components documentation, i mean detailed documentation of, for example, create one RecorderEndpoint, what params it takes etc. In oficial site documentation they send you to see the demos, but demos may have differences with whatever you want to do.

**Comment by Jerameel** [comment]
https://github.com/Kurento/kurento-tutorial-java/tree/master/kurento-group-call. Just use the method how the sample Echo client connects...
